export const types = {
  ADD_FAVORITE : 'ADD_FAVORITE',
  DELETE_FAVORITE : 'DELETE_FAVORITE',
  DELETE_REQUEST: 'DELETE_REQUEST',
  CANCEL_REQUEST: 'CANCEL_REQUEST',
  DELETE_CONFIRMATION: 'DELETE_CONFIRMATION',
  FLAG_FAVORITES: 'FLAG_FAVORITES'
}